name: Develop Workflow

on:
  push:
    branches:
      - develop
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Security scan
        run: echo "Running check"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Build
        run: |
          docker build -t thenafiz/meditrack:latest .

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u thenafiz --password-stdin 

      - name: Docker Push
        run: |
          docker push thenafiz/meditrack:latest
