name: Develop Workflow

on:
  push:
    branches:
      - develop
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Security scan
        run: echo "Running check"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Build
        run: docker build -t meditrack:latest .